import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'

import { Inter } from 'next/font/google'

import './globals.css'
import { DEFAULT_LANGUAGE } from '@/common/constants'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function LangLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale: string }>
}>) {
  const { locale } = await params

  return (
    <html lang={locale || DEFAULT_LANGUAGE} data-theme="light">
      <body className={inter.className} suppressHydrationWarning>
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  )
}
